# Generated by Django 3.2.9 on 2021-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='movie', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
